# This tool will verify the health of application
# in this config, heartbeat will ping application every five seconds

heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200
    - http://kibana:5601
    - http://app:8000

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana
    - apm
    - metricbeat

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: 'elastic'
  password: 'changeme'